// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yktfiqenepodgcusltzv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlrdGZpcWVuZXBvZGdjdXNsdHp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMjc4MDksImV4cCI6MjA2NDgwMzgwOX0.n1-iulHuSY2UzVxf19rDIHRb6xALxBpJNWNcdAVv8i4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);